### ISSUE TITLE
Got this on Mac

### ISSUE THREAD

**Issue by dioptre** [jkuri/opencv-ffmpeg-rtmp-stream#6]
```
RTMP_Connect0, failed to connect socket. 61 (Connection refused)
```

Please help!

**Comment by dioptre** [comment]
Ah I'm an idiot I thought this was an rtmp streamer - as ffmpeg does it - needed the docker rtmp-server

**Comment by jkuri** [comment]
no problem. if you wish customized RTMP server you can check out https://github.com/nareix/joy4. I used that library for docker image.
