### ISSUE TITLE
Cant Stream Higher Resolutions(Windows10)x64

### ISSUE THREAD

**Issue by batuhannzorlu** [jkuri/opencv-ffmpeg-rtmp-stream#9]
Hi,
I have built the project on windows10(x64), using prebuilt ffmpeg libraries. Project is woking smoothly, but the problem is i can not get higher resolutions than 800x600,(it works with lower resolutions). Application does not return anything to debug
![pic](https://user-images.githubusercontent.com/37422935/182436896-121473df-3f31-49fa-be1a-15d217259f04.PNG)
.

**Comment by jkuri** [comment]
Try running with `--log` option, it might produce some more information. By the way, it is possible that your camera doesn't support that resolution and fps combination, I noticed that already with my camera. Try changing framerate to 24 or some other value and let me know if it helps.

**Comment by batuhannzorlu** [comment]
I have  double checked  camera's FPS and resolution. And that is not the problem. My camera supports. Also i have tried the --log true flag but doesnt help either.(it gives the exact same output as 800x600.Doesnt display any error.)

**Comment by jkuri** [comment]
I honestly don’t know how to help you. You can try to play around with
bitrate and profile parameters, but I am not sure.

**Comment by batuhannzorlu** [comment]
i am writing this, for future readers, the code is buggy. The problem is appereantly  related to memory allocation.

AVFrame *allocate_frame_buffer(AVCodecContext *codec_ctx, double width, double height)
{
	AVFrame *frame_ = av_frame_alloc();
	int i = av_image_get_buffer_size(codec_ctx->pix_fmt, width, height, 1);
	//std::vector<uint8_t> framebuf(av_image_get_buffer_size(codec_ctx->pix_fmt, width, height, 1));
	uint8_t* pFrmBufer = new uint8_t[i];
	av_image_fill_arrays(frame_->data, frame_->linesize, pFrmBufer/*framebuf.data()*/, codec_ctx->pix_fmt, width, height, 1);
	frame_->width = width;
	frame_->height = height;
	frame_->format = static_cast<int>(codec_ctx->pix_fmt);

	return frame_;
}
Just create the  uint8_t pointer rather than vector<uint8_t>, because it is a local variable(in stack ) and it is always deleted after out of the function. @jkuri  please also update your function. thanks.

**Comment by jkuri** [comment]
hi, thanks for this! can you please create a pull request with that fix?
